apiVersion: v1
kind: Service
metadata:
  name: nextjsbasicapp
  namespace: nextjsbasicapp
  labels:
    app: nextjsbasicapp
spec:
  type: ClusterIP  # Default type, suitable for use with Ingress
  selector:
    app: nextjsbasicapp
  ports:
    - name: http
      protocol: TCP
      port: 80         # Service port (used by Ingress)
      targetPort: 3000 # Container port (Next.js app listens here)
